### ISSUE TITLE
🔥实现互动服务

### ISSUE THREAD

**Issue by Yziyan** [Go-To-Byte/DouSheng#13]
![image](https://user-images.githubusercontent.com/101268302/218300399-b0e8774b-16cd-4702-932b-a6f8498b0596.png)

1. 互动方面所需接口的基本功能
2. 能够组合其他服务
3. 调优与代码优化
4. 至于拆两个服务、还是一个服务，都合理，怎么方便怎么来。只要咱们不写

**Comment by SmartBest-Yang** [comment]
- [x] 点赞/取消点赞 RPC接口实现
- [ ] 点赞/取消点赞 RPC客户端实现
- [ ] 点赞/取消点赞 网关相关实现
- [ ] 获取点赞视频列表 RPC接口实现
- [ ] 获取点赞视频列表 RPC客户端实现
- [ ] 获取点赞视频列表 网关相关实现
- [ ] 发送评论/删除评论 RPC接口实现
- [ ] 发送评论/删除评论 RPC客户端实现
- [ ] 发送评论/删除评论 网关相关实现
- [ ] 获取评论列表 RPC接口实现
- [ ] 获取评论列表 RPC客户端实现
- [ ] 获取评论列表 网关相关实现

**Comment by SmartBest-Yang** [comment]
- [ ] 获取评论总数RPC接口
- [ ] 获取视频点赞数RPC接口
