### ISSUE TITLE
🚧实现聊天相关服务

### ISSUE THREAD

**Issue by Yziyan** [Go-To-Byte/DouSheng#15]
![image](https://user-images.githubusercontent.com/101268302/218300609-e1e7feb8-10ef-4c2a-81e7-7be1f2f19c55.png)

实现聊天服务的基础功能，这个可以慢慢做。上次上风好像说她在写这个聊天相关的。可以看看是否感兴趣~

官方给出的参考方案哪种方便、熟悉，就可以。

也可以自己的方式去实现~

**Comment by WWWindrunner** [comment]
分支已合并
