### ISSUE TITLE
请问您还留着简易版抖音apk吗？

### ISSUE THREAD

**Issue by molu-ggg** [Go-To-Byte/DouSheng#52]
请问您还留着简易版抖音apk吗？

**Comment by SmartBest-Yang** [comment]
您好，未经授权我们无法直接提供安装包，建议您联系字节青训营官方工作人员或者在官方提供的下载链接中获取安装包

**Comment by SmartBest-Zhi** [comment]
> 请问您还留着简易版抖音apk吗？

您好，未经授权我们无法直接提供安装包，建议您联系字节青训营官方工作人员或者在官方提供的下载链接中获取安装包
